#loltravis
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#before install
before_install:
  - sudo apt-get update
  - sudo apt-get install aria2
# command to install dependencies
install: 
  - pip install . -r requirements.txt --upgrade
# command to run tests
script:
  - python setup.py test